import base64
import logging
import os
import time
import requests
from dotenv import load_dotenv
from services.retry import retry_with_backoff

load_dotenv()
logger = logging.getLogger("gh-pr-agent.github")


def check_rate_limit(response: requests.Response) -> None:
    remaining = response.headers.get("X-RateLimit-Remaining")
    reset_time = response.headers.get("X-RateLimit-Reset")

    if remaining is not None:
        remaining_int = int(remaining)
        if remaining_int < 50:
            reset_str = (
                time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(reset_time)))
                if reset_time
                else "unknown"
            )
            logger.warning(
                f"🚨 GitHub API Rate Limit critically low: {remaining_int} requests remaining. Resets at {reset_str}"
            )
        elif remaining_int < 200:
            logger.info(f"ℹ️ GitHub API Rate Limit remaining: {remaining_int}")


@retry_with_backoff(max_retries=3, base_delay=1.5, retryable_exceptions=(requests.RequestException,))
def post_issue_comment(repo_full_name: str, issue_number: int, comment_text: str) -> bool:
    token = os.getenv("GITHUB_TOKEN")
    url = f"https://api.github.com/repos/{repo_full_name}/issues/{issue_number}/comments"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "AI-PR-Reviewer-Bot",
    }
    body = f"### 🤖 AI Assistant Response\n\n{comment_text}\n\n---\n*Response generated by @pr-bot*\n"

    response = requests.post(url, headers=headers, json={"body": body}, timeout=10)
    check_rate_limit(response)
    return response.status_code == 201


@retry_with_backoff(max_retries=3, base_delay=1.5, retryable_exceptions=(requests.RequestException,))
def submit_formal_pr_review(
    repo_full_name: str,
    pr_number: int,
    commit_id: str,
    review_summary: str,
    is_approved: bool,
    comments: list,
    valid_lines_map: dict[str, set[int]] | None = None,
) -> bool:
    token = os.getenv("GITHUB_TOKEN")
    url = f"https://api.github.com/repos/{repo_full_name}/pulls/{pr_number}/reviews"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "AI-PR-Reviewer-Bot",
    }

    inline_payload = []
    out_of_bounds_comments = []

    for c in comments:
        is_valid = True
        if valid_lines_map is not None:
            file_valid_lines = valid_lines_map.get(c.path, set())
            if c.line not in file_valid_lines:
                is_valid = False

        if is_valid:
            comment_body = f"**[{c.severity}]** {c.comment}"
            if c.suggested_patch:
                comment_body += f"\n\n```suggestion\n{c.suggested_patch.strip()}\n```"

            inline_payload.append({
                "path": c.path,
                "line": c.line,
                "side": "RIGHT",
                "body": comment_body,
            })
        else:
            out_of_bounds_comments.append(f"- **[{c.severity}]** `{c.path}:{c.line}`: {c.comment}")

    badge = "✅ **LGTM / Approved**" if is_approved else "⚠️ **Action Required / Changes Requested**"
    extra_notes = ("\n\n### 📝 Additional File Comments:\n" + "\n".join(out_of_bounds_comments)) if out_of_bounds_comments else ""
    review_body = f"### 🤖 AI Code Review Summary\n\n**Verdict:** {badge}\n\n{review_summary}{extra_notes}\n\n---\n*Automated review submitted by AI PR Review Agent*\n"

    payload = {
        "commit_id": commit_id,
        "body": review_body,
        "event": "COMMENT",
        "comments": inline_payload,
    }

    res = requests.post(url, headers=headers, json=payload, timeout=10)
    check_rate_limit(res)

    if res.status_code in (200, 201):
        return True

    logger.warning(f"Formal review failed ({res.status_code}): {res.text}. Falling back to standard issue comment...")
    fallback_url = f"https://api.github.com/repos/{repo_full_name}/issues/{pr_number}/comments"
    fallback_res = requests.post(fallback_url, headers=headers, json={"body": review_body}, timeout=10)
    check_rate_limit(fallback_res)
    return fallback_res.status_code == 201


@retry_with_backoff(max_retries=3, base_delay=1.5, retryable_exceptions=(requests.RequestException,))
def create_patch_branch_and_pr(
    repo_full_name: str,
    original_pr_number: int,
    base_branch: str,
    commit_msg: str,
    pr_description: str,
    files: list,
) -> str | None:
    token = os.getenv("GITHUB_TOKEN")
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "AI-PR-Reviewer-Bot",
    }

    ref_url = f"https://api.github.com/repos/{repo_full_name}/git/ref/heads/{base_branch}"
    ref_res = requests.get(ref_url, headers=headers, timeout=10)
    check_rate_limit(ref_res)
    if ref_res.status_code != 200:
        logger.error(f"Failed to get base branch SHA: {ref_res.text}")
        return None
    base_sha = ref_res.json()["object"]["sha"]

    new_branch = f"ai-fix/pr-{original_pr_number}"
    create_ref_url = f"https://api.github.com/repos/{repo_full_name}/git/refs"
    create_ref_res = requests.post(
        create_ref_url,
        headers=headers,
        json={"ref": f"refs/heads/{new_branch}", "sha": base_sha},
        timeout=10,
    )
    check_rate_limit(create_ref_res)

    if create_ref_res.status_code not in (201, 422):
        logger.error(f"Failed to create branch: {create_ref_res.text}")
        return None

    for file_obj in files:
        contents_url = f"https://api.github.com/repos/{repo_full_name}/contents/{file_obj.path}?ref={new_branch}"
        c_res = requests.get(contents_url, headers=headers, timeout=10)
        check_rate_limit(c_res)
        file_sha = c_res.json().get("sha") if c_res.status_code == 200 else None

        put_payload = {
            "message": commit_msg,
            "content": base64.b64encode(file_obj.content.encode("utf-8")).decode("utf-8"),
            "branch": new_branch,
        }
        if file_sha:
            put_payload["sha"] = file_sha

        put_res = requests.put(contents_url.split("?")[0], headers=headers, json=put_payload, timeout=10)
        check_rate_limit(put_res)
        if put_res.status_code not in (200, 201):
            logger.error(f"Failed to commit file {file_obj.path}: {put_res.status_code} - {put_res.text}")
            return None

    pr_url = f"https://api.github.com/repos/{repo_full_name}/pulls"
    pr_payload = {
        "title": f"🤖 [Auto-Fix] Remediate issues from PR #{original_pr_number}",
        "head": new_branch,
        "base": base_branch,
        "body": f"## 🤖 Automated Remediation Patch\n\nAddresses review findings in PR #{original_pr_number}.\n\n### Summary:\n{pr_description}\n\n---\n*Generated by AI PR Review Agent*",
    }

    pr_res = requests.post(pr_url, headers=headers, json=pr_payload, timeout=10)
    check_rate_limit(pr_res)
    if pr_res.status_code == 201:
        pr_html_url = pr_res.json().get("html_url")
        logger.info(f"Auto-Fix PR created: {pr_html_url}")
        return pr_html_url
    elif pr_res.status_code == 422:
        logger.info("Auto-Fix PR already open for this branch.")
        return None
    return None